platform:ios, '7.0'

inhibit_all_warnings!

pod 'SASlideMenu','2.0.3'
pod 'SVProgressHUD','1.1.3'
pod 'AFNetworking','2.6.0'
pod 'JSONKit-NoWarning','1.2'
pod 'BrightSDK','3.3.4'
pod 'FDWaveformView','0.3.1'
pod 'UMengAnalytics-NO-IDFA', '3.6.7'
pod 'Bugtags'
pod 'MJRefresh'
